### ISSUE TITLE
Can't decompress files on download

### ISSUE THREAD

**Issue by thegargiulian** [BuzzFeedNews/2015-08-immigrant-detention#17]
immigration-data.tar.gz-X files can't be decompressed upon download (using macOS Mojave 10.14.5). Removing the -X at the end and trying to decompress does not resolve issue. Can the files be re-uploaded in the form immigration-data.-X.tar.gz?

**Comment by jsvine** [comment]
Hi @mgargiulo, can you describe the steps you've taken?

You might already have seen this in the README.md, but just in case not:

> Because the raw data occupies 5.3 gigabytes of storage, this repository contains a compressed version of it. To decompress the data, run `make data` from this repository's root directory.
